<template>
  <modal
    name="authenticator-dialog"
    :width="824"
    height="auto"
    :scrollable="true"
    :adaptive="true"
    transition=""
    class="section-modal authenticator-modal"
  >
    <div
      class="modal-close"
      @click="$modal.hide('authenticator-dialog')"
    >
      <CloseIcon />
    </div>
    <div class="row">
      <h2 class="w700 poppins t-33" style="margin-bottom: 17px">Authenticator Verification</h2>
      <div class="col-12">
        <h4 class="t-30 w500 lh-60 mb-0">Enter the Secret Key</h4>
        <p class="t-30 w700 lh-60 mb-0">VDGHT J3ON CEAE VK4R</p>
        <p class="t-19 lh-24">Complete de setup by entering the secret key into the field provided in your authenticator app.</p>
        <input type="text" class="text-center" placeholder="Enter the code generated by your authenticator app">
      </div>
      <div class="btns">
        <button class="btn roboto btn-hover">Submit</button>
      </div>
    </div>
  </modal>
</template>

<script>
import CloseIcon from "../icons/CloseIcon.vue";

export default {
  name: "EditPhoneModal",
  components: {
    CloseIcon
  }
};
</script>

<style lang="scss" scoped>
label {
  font-size: 26px;
  line-height: 30px;
  color: #000000;
  font-weight: 700;
}
input {
  margin-bottom: 20px;
  width: 100%;
  height: 73px;
  background: #E5E5E5;
  border-radius: 5px;
  font-size: 22px;
  padding: 0 17px;
  color: #333333;
  &::placeholder {
    font-size: 22px;
    font-weight: 500;
    color: #333333;
  }
  border: none;
}
.modal-close {
  padding: 0 !important;
  top: 31px !important;
  right: 31px !important;
}

.row {
  margin: 10px 20px 0px 20px;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;

  .btns {
    width: 100%;
    display: flex;
    justify-content: center;
    margin-top: 10px;
    margin-bottom: 20px;

    .btn {
      margin: 0 !important;
      height: 83.34px;
      width: 284.25px;
      background: #F2A91C;
      border-radius: 15px;
      font-size: 24px;
      border: none;
      color: #000000;
      font-weight: 500;
    }
  }

  h2 {
    width: 100%;
    text-align: center;
    line-height: 54px;
  }
}
</style>

