<template>
  <div class="container c-tab">
    <div class="c-title">
      <p class="t-24 lh-36 w500 mb-0">User Info</p>
    </div>
    <div class="user-id">
      <p class="t-24 lh-36 w500 mb-0">User ID</p>
      <p class="t-18 lh-23 t-color2 mb-0" style="margin-top: 15px">{{userProfile.login}}</p>
    </div>
    <div class="d-flex flex-wrap mx-0 full-name">
      <div class="w-100">
        <p class="t-24 lh-36 w500 mb-0 d-flex align-items-center justify-content-between">
          <span>
            Full Name
          </span>
          <button @click="$modal.show('edit-fullname-dialog')" class="edit-icon"
                  style="position: relative; margin-left: 10px">
            <EditIcon />
          </button>
        </p>
        <p class="t-18 lh-23 t-color2 mb-0" style="margin-top: 15px">{{userProfile.full_name}}</p>
      </div>
    </div>
    <div class="d-flex flex-wrap mx-0 email">
      <div class="w-100">
        <p class="t-24 lh-36 w500 mb-0 d-flex align-items-start justify-content-between">
          <span>
            Email
          </span>
          <button @click="$modal.show('edit-email-dialog')" class="edit-icon"
                  style="position: relative; margin-left: 10px">
            <EditIcon />
          </button>
        </p>
        <p class="t-18 lh-23 t-color2 mb-0" style="margin-top: 15px">{{userProfile.email}}</p>
      </div>
    </div>
    <div class="c-title">
      <p class="t-24 lh-36 w500 mb-0">Password</p>
    </div>
    <div class="d-flex flex-wrap mx-0 password">
      <div class="w-100">
        <p class="t-24 lh-36 w500 mb-0 d-flex align-items-start justify-content-between">
          <span>
            Password
          </span>
          <button @click="$modal.show('edit-password-dialog')" class="edit-icon"
                  style="position: relative; margin-left: 10px">
            <EditIcon />
          </button>
        </p>
        <p class="t-18 lh-23 t-color2 mb-0" style="margin-top: 15px">********************</p>
      </div>
    </div>
    <div class="d-flex flex-wrap ">
        <div class="w-100">
          <div class="t-24 lh-36 w500 mb-0 d-flex align-items-start justify-content-between">
            <span>
              Authenticator App Code
            </span>
            <div class="custom-switch custom-switch-y on-off">
              <input type="checkbox" class="custom-control-input" id="authenticator" checked />
              <label for="authenticator"></label>
            </div>
          </div>
          <p class="t-18 lh-23 t-color2 mb-0" style="margin-top: 15px;">Enter the code generated by your authenticator app to confirm it is you.</p>
        </div>
    </div>

  </div>
</template>

<script>
import EditIcon from "../icons/EditIcon";

export default {
  name: "GeneralTab",
  props: {
    userProfile: {
      type: Object,
      required: true
    }
  },
  components: {
    EditIcon
  }
};
</script>
<style>
  .settings-rebranded .custom-switch.custom-switch-y.on-off{
    overflow: hidden;
  }
  .settings-rebranded .custom-switch.custom-switch-y.on-off input:checked + label:after{
    content: 'on';
    text-indent: -42px;
    text-shadow: 0 -1px 0 rgb(0 0 0 / 50%);
    font-weight: 400;
    font-size: 18px;
    color: rgba(0, 0, 0, 0.8);
    line-height: 40px;
    text-transform: uppercase;
  }
  .settings-rebranded .custom-switch.custom-switch-y.on-off label:after{
    content: 'Off';
    text-shadow: 0 -1px 0 rgb(0 0 0 / 50%);
    font-weight: 400;
    font-size: 18px;
    color: rgba(0, 0, 0, 0.8);
    line-height: 45px;
    text-indent: 50px;
    text-transform: uppercase;
  }
</style>
